"""empty message

Revision ID: 18e2e22531e9
Revises: a41b8e3665b7
Create Date: 2022-05-29 18:40:08.250160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18e2e22531e9'
down_revision = 'a41b8e3665b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comix_pages', 'params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix_pages', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
