"""empty message

Revision ID: 1f6d3c6eac0e
Revises: dbfd141b247e
Create Date: 2022-04-24 14:20:18.754666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6d3c6eac0e'
down_revision = 'dbfd141b247e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comix_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comix_pages')
    # ### end Alembic commands ###
