"""empty message

Revision ID: 21acebe2892e
Revises: 7e1b1e30a57a
Create Date: 2022-04-26 20:03:27.913563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21acebe2892e'
down_revision = '7e1b1e30a57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix_pages', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comix_pages', 'params')
    # ### end Alembic commands ###
