"""empty message

Revision ID: 31f1462708ef
Revises: 97253c9436a2
Create Date: 2022-05-14 21:38:53.265485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f1462708ef'
down_revision = '97253c9436a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix', sa.Column('autor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comix', 'autor', ['autor_id'], ['id'])
    op.drop_column('comix', 'autor')
    op.add_column('comix_pages', sa.Column('comix_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comix_pages', 'comix', ['comix_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comix_pages', type_='foreignkey')
    op.drop_column('comix_pages', 'comix_id')
    op.add_column('comix', sa.Column('autor', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comix', type_='foreignkey')
    op.drop_column('comix', 'autor_id')
    # ### end Alembic commands ###
