"""empty message

Revision ID: 7e1b1e30a57a
Revises: 1f6d3c6eac0e
Create Date: 2022-04-26 19:57:20.887253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1b1e30a57a'
down_revision = '1f6d3c6eac0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comix_pages', sa.Column('elements', sa.JSON(), nullable=True))
    op.add_column('comix_pages', sa.Column('coordinates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comix_pages', 'coordinates')
    op.drop_column('comix_pages', 'elements')
    op.drop_table('autor')
    # ### end Alembic commands ###
