"""empty message

Revision ID: 97253c9436a2
Revises: 21acebe2892e
Create Date: 2022-04-26 20:12:50.748760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97253c9436a2'
down_revision = '21acebe2892e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comix_pages', 'params')
    op.drop_column('comix_pages', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix_pages', sa.Column('coordinates', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comix_pages', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
