"""empty message

Revision ID: a41b8e3665b7
Revises: 31f1462708ef
Create Date: 2022-05-29 18:10:01.368757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41b8e3665b7'
down_revision = '31f1462708ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix_pages', sa.Column('params', sa.JSON(), nullable=True))
    op.drop_column('comix_pages', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comix_pages', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('comix_pages', 'params')
    # ### end Alembic commands ###
